### ISSUE TITLE
Replace input cuts off

### ISSUE THREAD

**Issue by intercepti0n** [TheOld/vscode-fluent-ui#56]
About a year ago i've encountered this problem for the first and it is still there. For some reason replace input filed just goes offscreen and that's a bit sad 'cause I love this extension.

![image](https://github.com/TheOld/vscode-fluent-ui/assets/137328283/cae080fd-5522-4218-b077-5a806fa11a0c)

**Comment by MrTadeu** [comment]
Me too, i really appreciate this extension, but I've encountered a couple of bugs. To address one of them, I had to perform a CSS injection in "C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\electron-sandbox\workbench\workbench.html." I added the following code:
```css
<style>
  .tabs-container {
    height: 32px !important;
  }

  .tabs-container.has-text {
    height: auto !important;
    width: auto !important;
    max-width: 97% !important;
  }

  .replace-input {
    max-width: calc(100% - 60px) !important;
 }
</style>
```
The first two classes address a bug related to the terminal, while the other one tackle this issue. I hope this can be helpful in resolving these issues. Note: I understand that this may not be the ideal solution, but for now, it has successfully addressed the issues I was facing.
